//! Decoding of Kafka connector state (source reader splits, enumerator/coordinator, sink).
//! Reads tests/fixtures/savepoint-kafka (generated by KafkaSavepointGeneratorIT); skips if absent.
use std::path::Path;

use flink_explorer::index::builder::build_index;
use flink_explorer::index::cache::IndexCache;
use flink_explorer::parser;
use flink_explorer::tui::tree::TreeView;
use ratatui::backend::TestBackend;
use ratatui::layout::Rect;
use ratatui::widgets::Block;
use ratatui::Terminal;

const SAVEPOINT_DIR: &str = "tests/fixtures/savepoint-kafka";

fn load_index() -> Option<IndexCache> {
    let dir = Path::new(SAVEPOINT_DIR);
    let mpath = dir.join("_metadata");
    if !mpath.exists() {
        eprintln!("skip: no savepoint-kafka fixture (run `cd test-flink-job && mvn verify`)");
        return None;
    }
    let sp = parser::parse_metadata(&mpath).unwrap();
    let meta = std::fs::metadata(&mpath).unwrap();
    Some(build_index(&sp, meta.len(), 0, dir))
}

/// Collect the first decoded element label of a named operator state.
fn op_state_label(index: &IndexCache, name: &str) -> Option<String> {
    for op in &index.operators {
        for s in &op.states {
            if s.name == name {
                if let Some(e) = s.entries.first() {
                    return Some(String::from_utf8_lossy(&e.key).into_owned());
                }
            }
        }
    }
    None
}

#[test]
fn kafka_source_reader_splits_decode() {
    let index = match load_index() {
        Some(i) => i,
        None => return,
    };
    let mut splits = Vec::new();
    for op in &index.operators {
        for s in &op.states {
            if s.name == "SourceReaderState" {
                for e in &s.entries {
                    splits.push(String::from_utf8_lossy(&e.key).into_owned());
                }
            }
        }
    }
    assert!(!splits.is_empty(), "expected SourceReaderState splits");
    assert!(
        splits
            .iter()
            .all(|s| s.contains("explorer-input-") && s.contains("start=")),
        "splits decode to topic-partition + offset: {:?}",
        splits
    );
    println!("reader splits: {:?}", splits);
}

#[test]
fn kafka_sink_writer_state_decodes() {
    let index = match load_index() {
        Some(i) => i,
        None => return,
    };
    let w = op_state_label(&index, "writer_raw_states").expect("writer_raw_states present");
    assert!(
        w.contains("transactionalIdPrefix=explorer-txn"),
        "writer state: {}",
        w
    );
}

#[test]
fn kafka_source_enumerator_decodes() {
    let index = match load_index() {
        Some(i) => i,
        None => return,
    };
    let info = index
        .operators
        .iter()
        .find_map(|o| o.coordinator_info.as_ref())
        .expect("a source operator with decoded enumerator coordinator state");
    assert!(
        info.contains("explorer-input-") && info.contains("initialDiscoveryFinished"),
        "enumerator decode: {}",
        info
    );
    println!("enumerator: {}", info);
}

#[test]
fn kafka_sink_committer_decodes_pending_transaction() {
    let index = match load_index() {
        Some(i) => i,
        None => return,
    };
    let mut labels = Vec::new();
    for op in &index.operators {
        for s in &op.states {
            if s.name == "streaming_committer_raw_states" {
                for e in &s.entries {
                    labels.push(String::from_utf8_lossy(&e.key).into_owned());
                }
            }
        }
    }
    assert!(
        !labels.is_empty(),
        "expected streaming_committer_raw_states"
    );
    // The IT keeps producing through the savepoint, so at least one subtask has an open
    // transaction whose KafkaCommittable decodes to a transactional id + producerId + epoch.
    let pending: Vec<&String> = labels
        .iter()
        .filter(|l| l.contains("pending transaction"))
        .collect();
    assert!(
        pending.iter().any(|l| l.contains("explorer-txn")
            && l.contains("producerId=")
            && l.contains("epoch=")),
        "committer should decode a pending KafkaCommittable precisely: {:?}",
        labels
    );
    println!("committer states: {:?}", labels);
}

/// Drive the real `TreeView` widget: expand the whole tree and render it to a `TestBackend`,
/// then assert the decoded Kafka labels actually reach the screen (not just the cache).
#[test]
fn kafka_states_render_in_the_tui() {
    let index = match load_index() {
        Some(i) => i,
        None => return,
    };
    // Default view (hide_empty = true): the Kafka source/sink operators have only operator
    // state, so this also guards that they aren't hidden.
    let mut tv = TreeView::new(&index);
    // Expand every node: a few passes over the (growing) flat list.
    for _ in 0..6 {
        tv.jump_first();
        for _ in 0..256 {
            tv.expand();
            tv.move_down();
        }
    }
    tv.jump_first();

    let backend = TestBackend::new(120, 400);
    let mut terminal = Terminal::new(backend).unwrap();
    terminal
        .draw(|f| tv.render(f, Block::default(), Rect::new(0, 0, 120, 400)))
        .unwrap();

    let buf = terminal.backend().buffer();
    let mut screen = String::new();
    for y in 0..buf.area.height {
        for x in 0..buf.area.width {
            screen.push_str(buf[(x, y)].symbol());
        }
        screen.push('\n');
    }

    assert!(
        screen.contains("explorer-input-"),
        "source reader splits / enumerator partitions should render:\n{}",
        screen
    );
    assert!(
        screen.contains("transactionalIdPrefix=explorer-txn"),
        "Kafka sink writer prefix should render:\n{}",
        screen
    );
    assert!(
        screen.contains("pending transaction: explorer-txn")
            && screen.contains("producerId=")
            && screen.contains("epoch="),
        "committer's decoded KafkaCommittable should render:\n{}",
        screen
    );
    assert!(
        screen.contains('📨'),
        "Kafka operators/states should be flagged with the 📨 icon:\n{}",
        screen
    );
}
